### ISSUE TITLE
Cant update the firmware Ver.1.11.5 or any other

### ISSUE THREAD

**Issue by dadooo123** [OpenAstroTech/OATFWGUI#35]
![image](https://github.com/OpenAstroTech/OATFWGUI/assets/73754547/99531aa5-3b85-4966-8d52-918e90b282ef)
[oat_fw_gui_2023-11-08-16-45-36.log](https://github.com/OpenAstroTech/OATFWGUI/files/13298707/oat_fw_gui_2023-11-08-16-45-36.log)

**Comment by julianneswinoga** [comment]
Looks like your computer can't reset the board. Double check you have the right COM port and that you removed the capacitor? :slightly_smiling_face:

**Comment by dadooo123** [comment]
what is capacitor and how do i turn it off?

**Comment by julianneswinoga** [comment]
Shown here in the second picture: https://wiki.openastrotech.com/en/OpenAstroTracker/Kit-update#hardware-preparation

**Comment by dadooo123** [comment]
Alright thankyoufor the answer i will try it:)

**Comment by julianneswinoga** [comment]
Hey @dadooo123 just checking in, were you able to flash the firmware after removing the capacitor? :slightly_smiling_face:

**Comment by dadooo123** [comment]
Yes i was able to update the firmware after doing that,thank you so much:)
