### ISSUE TITLE
Error while uploading firmware

### ISSUE THREAD

**Issue by Skypix11** [OpenAstroTech/OATFWGUI#4]
My setup:
- Arduino Mega 2560
- LCD Shield with Keypad
- GPS NEO-6M
- 28BYJ-48 Stepper

Everthing worked until I tried to upload the generic Mega2560 (aka RAMPS) Firmware. I could not figure it out what the issue was.
![image](https://user-images.githubusercontent.com/10564872/200144801-b7805f4d-0f76-4c3c-af1d-4eeae0de5817.png)

Log:
[oat_fw_gui_2022-11-05-23-47-01.log](https://github.com/OpenAstroTech/OATFWGUI/files/9944845/oat_fw_gui_2022-11-05-23-47-01.log)

**Comment by julianneswinoga** [comment]
Hey thank you so much for the bug report! (and for attaching the log, super helpful :smile: )
Could you try the linked build? *Should* fix the upload issue
https://github.com/OpenAstroTech/OATFWGUI/suites/9152708675/artifacts/425859371
